import crypto from "crypto";

import { UserIdentity } from "@mml-io/3d-web-user-networking";
import type {
  CharacterDescription,
  UserData,
} from "@mml-io/3d-web-user-networking";
import { jwtDecode } from "jwt-decode";

export type AuthUser = {
  // clientId is the connection identifier for the user - it is null before the client websocket is connected
  clientId: number | null;
  // userData is the user's presentation in the world (username and character description)
  userData?: UserData;
  // sessionToken is the token that is generated by this authenticator and the user uses to authenticate their websocket connection
  sessionToken: string;
  // other page user subject - this is the user's uuid
  sub?: string;
};

export type OtherPageAuthenticatorOptions = Record<string, any>;

const defaultOptions: OtherPageAuthenticatorOptions = {};

export class OtherPageAuthenticator {
  private usersByClientId = new Map<number, AuthUser>();
  private userBySessionToken = new Map<string, AuthUser>();

  constructor(
    private defaultCharacter: CharacterDescription,
    private options: OtherPageAuthenticatorOptions = defaultOptions,
  ) {}

  async generateAuthorizedSessionToken(): Promise<string | null> {
    console.log("Generating session token");
    const sessionToken = crypto.randomBytes(20).toString("hex");
    const authUser: AuthUser = {
      clientId: null,
      sessionToken,
    };

    this.userBySessionToken.set(sessionToken, authUser);
    return Promise.resolve(sessionToken);
  }

  public onClientConnect(
    clientId: number,
    sessionToken: string,
    userIdentityPresentedOnConnection?: UserIdentity,
  ): UserData | null {
    if (!sessionToken) {
      return null;
    }

    let user = this.userBySessionToken.get(sessionToken);
    if (!user) {
      let decoded: any;
      try {
        // TODO:attempt to decode and validate the idToken
        decoded = jwtDecode(sessionToken);
        // console.log("decoded", decoded);
      } catch (err) {
        console.error("Error decoding session token", err);
        return null;
      }

      // TODO: validate using jwks endpoint
      if (!decoded) {
        return null;
      }

      user = {
        clientId: null,
        sessionToken,
        sub: decoded.sub,
        userData: {
          username: decoded.username || decoded.avatar.name,
          characterDescription: decoded.avatar.mmlUrl
            ? {
                mmlCharacterUrl: decoded.avatar.mmlUrl,
              }
            : this.defaultCharacter,
        },
      };
      this.userBySessionToken.set(sessionToken, user);
    }

    if (user.clientId !== null) {
      console.error(`Session token already connected`);
      return null;
    }

    user.clientId = clientId;

    if (!user.userData) {
      user.userData = {
        username: `User ${clientId}`,
        characterDescription: this.defaultCharacter,
      };
    }

    if (userIdentityPresentedOnConnection) {
      console.warn("Ignoring user-identity on initial connect");
    }
    this.usersByClientId.set(clientId, user);
    return user.userData;
  }

  public getClientIdForSessionToken(
    sessionToken: string,
  ): { id: number } | null {
    const user = this.userBySessionToken.get(sessionToken);

    if (!user) {
      console.error("getClientIdForSessionToken - unknown session");
      return null;
    }
    if (user.clientId === null) {
      console.error("getClientIdForSessionToken - client not connected");
      return null;
    }
    return { id: user.clientId };
  }

  public getUserByClientId(clientId: number): AuthUser | undefined {
    return this.usersByClientId.get(clientId);
  }

  public onClientUserIdentityUpdate(): UserData | null {
    console.log(`onClientUserIdentityUpdate`);
    // This implementation does not allow updating user data after initial connect.

    // To allow updating user data after initial connect, return the UserData object that reflects the requested change.

    // Returning null will not update the user data.
    return null;
  }

  public onClientDisconnect(clientId: number) {
    console.log(`onClientDisconnect ${clientId}`);
    // TODO - expire session token after a period of disconnection
    const userData = this.usersByClientId.get(clientId);
    if (userData) {
      userData.clientId = null;
      this.usersByClientId.delete(clientId);
    }
  }
}
