import crypto from "crypto";

import { UserIdentity } from "@mml-io/3d-web-user-networking";
import type {
  CharacterDescription,
  UserData,
} from "@mml-io/3d-web-user-networking";
import { Request, Response } from "express";
import { jwtDecode } from "jwt-decode";

export type AuthUser = {
  // clientId is the connection identifier for the user - it is null before the client websocket is connected
  clientId: number | null;
  // userData is the user's presentation in the world (username and character description)
  userData?: UserData;
  // sessionToken is the token that is generated by this authenticator and the user uses to authenticate their websocket connection
  sessionToken: string;
  // other page user subject - this is the user's uuid
  sub?: string;
  // wallet address - this is the user's primary wallet address
  wallet?: string;
};

export type OtherPageAuthenticatorOptions = Record<string, any>;

const defaultOptions: OtherPageAuthenticatorOptions = {};

export class OtherPageAuthenticator {
  private usersByClientId = new Map<number, AuthUser>();
  private userBySessionToken = new Map<string, AuthUser>();

  constructor(
    private defaultCharacter: CharacterDescription,
    private options: OtherPageAuthenticatorOptions = defaultOptions,
  ) {}

  async generateAuthorizedSessionToken(req: Request): Promise<string | null> {
    const sessionToken = req.query._s as string;

    if (!sessionToken) {
      return Promise.resolve(null);
    }

    // validate the session
    let decoded: any;
    try {
      // TODO: validate the idToken expiration
      decoded = jwtDecode(sessionToken);
    } catch (err) {
      console.error("Error decoding session token", err);
      return null;
    }

    // TODO: validate using jwks endpoint
    if (!decoded) {
      return null;
    }

    const authUser: AuthUser = {
      clientId: null,
      sessionToken,
      sub: decoded.sub,
      wallet: decoded.wallet,
      userData: {
        username: decoded.avatar?.name || decoded.username || decoded.wallet,
        characterDescription:
          decoded.avatar?.mmlUrl || decoded.avatar?.mmlModel
            ? {
                mmlCharacterUrl: decoded.avatar.mmlUrl,
                meshFileUrl: decoded.avatar.mmlModel,
              }
            : this.defaultCharacter,
      },
    };

    this.setUserBySessionToken(sessionToken, authUser);

    return Promise.resolve(sessionToken);
  }

  public onClientConnect(
    clientId: number,
    sessionToken: string,
  ): UserData | null {
    console.log("onClientConnect", clientId);
    if (!sessionToken) {
      return null;
    }

    const user = this.userBySessionToken.get(sessionToken);
    if (!user?.userData) {
      return null;
    }

    this.setUserBySessionToken(sessionToken, {
      ...user,
      clientId,
    });
    this.setUserByClientId(clientId, {
      ...user,
      clientId,
    });

    return user.userData;
  }

  public getClientIdForSessionToken(
    sessionToken: string,
  ): { id: number } | null {
    if (!sessionToken) {
      return null;
    }
    const user = this.userBySessionToken.get(sessionToken);
    console.log("getClientIdForSessionToken", user?.clientId);

    if (!user) {
      console.error("getClientIdForSessionToken - unknown session");
      return null;
    }
    if (user.clientId === null) {
      console.error("getClientIdForSessionToken - client not connected");
      return null;
    }
    return { id: user.clientId };
  }

  public getUserByClientId(clientId: number): AuthUser | undefined {
    console.log("getUserByClientId", clientId);
    return this.usersByClientId.get(clientId);
  }

  public setUserByClientId(clientId: number, user: AuthUser) {
    console.log("setUserByClientId", clientId, user);
    this.usersByClientId.set(clientId, user);
  }

  private setUserBySessionToken(sessionToken: string, user: AuthUser) {
    this.userBySessionToken.set(sessionToken, user);
  }

  public onClientUserIdentityUpdate(
    clientId: number,
    data: any,
  ): UserData | null {
    console.log(`onClientUserIdentityUpdate`, clientId, data);
    // This implementation does not allow updating user data after initial connect.

    // To allow updating user data after initial connect, return the UserData object that reflects the requested change.

    // Returning null will not update the user data.
    return null;
  }

  public onClientDisconnect(clientId: number) {
    console.log(`onClientDisconnect ${clientId}`);
    // TODO - expire session token after a period of disconnection
    const userData = this.usersByClientId.get(clientId);
    if (userData) {
      userData.clientId = null;
      this.usersByClientId.delete(clientId);
      // this.userBySessionToken.delete(userData.sessionToken);
    }
  }

  public isValidToken(token: string): boolean {
    try {
      const decoded: any = jwtDecode(token);
      if (decoded && decoded.exp) {
        const currentTime = Math.floor(Date.now() / 1000);
        return currentTime < decoded.exp; // Check if the token is expired
      }

      // TODO: validate using jwks endpoint

      return false; // No exp claim means invalid token
    } catch (err) {
      return false; // Token is invalid
    }
  }
}
